import mongoose from "mongoose";

const profileViewSchema = new mongoose.Schema(
  {
    viewerUserId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Matrimony",
      required: true,
      index: true,
    },

    viewedUserId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Matrimony",
      required: true,
      index: true,
    },

    viewedProfileId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Matrimony",
      required: true,
      index: true,
    },

    // Used to identify a viewing event.
    // The value will be generated by ProfileService.
    viewKey: {
      type: String,
      required: true,
      index: true,
    },
  },
  {
    timestamps: true,
    collection: "profile_views",
  }
);

// ------------------------------------------------------------
// Existing lookup indexes
// ------------------------------------------------------------

profileViewSchema.index({
  viewedUserId: 1,
  viewerUserId: 1,
});

profileViewSchema.index({
  viewerUserId: 1,
  viewedUserId: 1,
  viewedProfileId: 1,
  createdAt: -1,
});

// ------------------------------------------------------------
// IMPORTANT
//
// This prevents two requests representing the SAME viewing
// event from being inserted simultaneously.
//
// ProfileService will generate the viewKey for the current
// 24-hour viewing window.
// ------------------------------------------------------------

profileViewSchema.index(
  {
    viewKey: 1,
  },
  {
    unique: true,
  }
);

const ProfileView =
  mongoose.models.ProfileView ||
  mongoose.model("ProfileView", profileViewSchema);

export default ProfileView;