// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa2KtXvRHDODfO67xZdP7AumvDJzPzcEM',
    appId: '1:588168780582:web:2cdbbe74c1d82e6637bfe7',
    messagingSenderId: '588168780582',
    projectId: 'matrimony-app-f8226',
    authDomain: 'matrimony-app-f8226.firebaseapp.com',
    storageBucket: 'matrimony-app-f8226.firebasestorage.app',
    measurementId: 'G-V81WY7MG5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYKcgNdF7yA2ou-e8IuBPo-gTDMkxIfXs',
    appId: '1:588168780582:android:9547738b978ba8cb37bfe7',
    messagingSenderId: '588168780582',
    projectId: 'matrimony-app-f8226',
    storageBucket: 'matrimony-app-f8226.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0jMiaOsGP2gkOxuxMKHcwLzeMtoXIwdY',
    appId: '1:588168780582:ios:02afc0eb26748fc237bfe7',
    messagingSenderId: '588168780582',
    projectId: 'matrimony-app-f8226',
    storageBucket: 'matrimony-app-f8226.firebasestorage.app',
    iosBundleId: 'com.example.matrimonyApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0jMiaOsGP2gkOxuxMKHcwLzeMtoXIwdY',
    appId: '1:588168780582:ios:02afc0eb26748fc237bfe7',
    messagingSenderId: '588168780582',
    projectId: 'matrimony-app-f8226',
    storageBucket: 'matrimony-app-f8226.firebasestorage.app',
    iosBundleId: 'com.example.matrimonyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa2KtXvRHDODfO67xZdP7AumvDJzPzcEM',
    appId: '1:588168780582:web:cfcef83136e1a2bb37bfe7',
    messagingSenderId: '588168780582',
    projectId: 'matrimony-app-f8226',
    authDomain: 'matrimony-app-f8226.firebaseapp.com',
    storageBucket: 'matrimony-app-f8226.firebasestorage.app',
    measurementId: 'G-V87Y94PEET',
  );
}
